using UnityEngine;

public class Wheel : MonoBehaviour
{
    private Rigidbody rb; // reference to the car's Rigidbody so we can apply suspension forces to the vehicle body

    [Header("Suspension")]
    public float restLength = 0.45f; // suspension length when the car is resting normally (equilibrium length of the spring)
    public float suspensionTravel = 0.20f; // maximum distance the suspension can move away from restLength (both compression and extension)
    public float springStrength = 60000f; // stiffness constant of the spring (Hooke's law coefficient k)
    public float damperStrength = 6500f; // damping coefficient used to resist rapid suspension motion

    private float minLength; // shortest possible suspension length (fully compressed suspension)
    private float maxLength; // longest possible suspension length (fully extended suspension)
    private float currentSpringLength; // suspension length measured during the current physics frame
    private float previousSpringLength; // suspension length from the previous physics frame (used to compute velocity)
    
    private Vector3 suspensionForce; // final force vector produced by the spring + damper system

    [Header("Wheel")]
    public float wheelRadius = 0.34f; // radius of the tire (used to convert raycast distance into suspension length)
    private Vector3 wheelLocalVelocity; // velocity of the wheel in local space (used for advanced traction calculations, not implemented in this basic suspension script)
    private Vector3 wheelWorldVelocity; // velocity of the wheel in world space (used for advanced traction calculations, not implemented in this basic suspension script)
    private float forwardVelocity; // component of the wheel's velocity in the forward direction (used for traction calculations, not implemented here)
    private float sidewaysVelocity; // component of the wheel's velocity in the sideways direction (used for traction calculations, not implemented here)
    void Start()
    {
        rb = transform.root.GetComponent<Rigidbody>(); // get the Rigidbody from the root object (the main car body)

        rb.centerOfMass = new Vector3(0, -0.35f, 0);

        minLength = restLength - suspensionTravel; // calculate the minimum suspension length when fully compressed

        maxLength = restLength + suspensionTravel;  // calculate the maximum suspension length when fully extended

        previousSpringLength = restLength; // initialize previous spring length so the first velocity calculation is stable
    }

    void FixedUpdate()
    {
        float rayLength = maxLength + wheelRadius; // maximum ray distance needed to detect the ground when suspension is fully extended

        float compression; // amount the spring is compressed relative to rest length

        float springForce; // force generated by the spring using Hooke's law

        float springVelocity; // speed at which the suspension length changes between frames

        float damperForce ; // force generated by the damper resisting suspension movement

        Debug.DrawRay(transform.position, -transform.up * rayLength, Color.red); // draw the suspension ray in the scene view for debugging

        if(Physics.Raycast(transform.position, -transform.up, out RaycastHit hit, rayLength))    // shoot a ray downward to detect ground contact within suspension range
        {
            Debug.DrawRay(hit.point, hit.normal, Color.green); // draw the ground surface normal where the ray hit

            currentSpringLength = hit.distance - wheelRadius; // convert hub-to-ground distance into actual suspension spring length

            currentSpringLength = Mathf.Clamp(currentSpringLength, minLength, maxLength); // restrict spring length within allowed suspension limits

            compression = restLength - currentSpringLength; // calculate how much the spring is compressed relative to its rest position

            springForce = compression * springStrength; // calculate spring force using Hooke's law (F = kx)

            springVelocity = (currentSpringLength - previousSpringLength) / Time.fixedDeltaTime; // calculate suspension velocity using change in length over time

            damperForce  = damperStrength * springVelocity; // compute damping force opposing suspension movement

            suspensionForce = Mathf.Max(0f, springForce - damperForce) * hit.normal; // combine spring and damper forces and apply them along the car's up direction

            Debug.DrawRay(transform.position, suspensionForce * 0.0005f, Color.blue);

            rb.AddForceAtPosition(suspensionForce,hit.point); // apply the suspension force to the Rigidbody at the wheel's contact location

            previousSpringLength = currentSpringLength; // store the current spring length for use in the next physics frame
            
            wheelWorldVelocity = rb.GetPointVelocity(hit.point); // get the velocity of the wheel's contact point in world space (used for potential traction calculations, not implemented here)
            wheelLocalVelocity = transform.InverseTransformDirection(wheelWorldVelocity); // convert world velocity to local space for potential traction calculations (not implemented here)

            forwardVelocity = wheelLocalVelocity.z; // extract forward velocity component (used for traction calculations, not implemented here)
            sidewaysVelocity = wheelLocalVelocity.x; // extract sideways velocity component (used for traction calculations

            Debug.DrawRay(hit.point, wheelWorldVelocity * 5f, Color.yellow); // draw the wheel's contact point velocity in world space for debugging
            Debug.DrawRay(hit.point, transform.forward * forwardVelocity * 5f, Color.blue); // draw the wheel's forward velocity component in local space for debugging 
            Debug.DrawRay(hit.point, transform.right * sidewaysVelocity * 5f, Color.cyan); // draw the wheel's sideways velocity component in local space for debugging
        }
        else
        {
            currentSpringLength = maxLength; // if the wheel is not touching ground, treat the suspension as fully extended

            previousSpringLength = currentSpringLength; // update previous length to avoid large velocity spikes when contact returns
        }

    }

    void Update()
    {
        
    }
}