using UnityEngine;
using UnityEngine.Rendering;

public class Wheel : MonoBehaviour
{
    // Reference to the car's Rigidbody.
    // All suspension and tire forces generated by this wheel
    // will be applied to this rigidbody.
    private Rigidbody rb;

    [Header("Suspension")]

    // The suspension length when the car is resting normally.
    // This is effectively the equilibrium length of the spring.
    public float restLength = 0.45f;

    // Maximum amount the suspension can compress or extend
    // relative to the rest length.
    public float suspensionTravel = 0.20f;

    // Spring stiffness constant (Hooke's law: F = kx).
    // Larger values produce a stiffer suspension.
    public float springStrength = 60000f;

    // Damping coefficient used to resist rapid suspension movement.
    // Prevents oscillation and bouncing.
    public float damperStrength = 6500f;

    // Minimum suspension length (fully compressed)
    private float minLength;

    // Maximum suspension length (fully extended)
    private float maxLength;

    // Current spring length measured this physics frame
    private float currentSpringLength;

    // Spring length from previous frame (used to compute suspension velocity)
    private float previousSpringLength;

    // Final suspension force produced by the spring + damper system
    private Vector3 suspensionForce;

    [Header("Wheel")]

    // Radius of the tire.
    // Used to convert raycast distance into suspension compression.
    public float wheelRadius = 0.34f;

    // Determines whether this wheel receives engine power.
    // Allows easy configuration of FWD / RWD / AWD vehicles later.
    public bool isDrivenWheel = true;

    // Velocity of the wheel contact point in world space
    private Vector3 wheelWorldVelocity;

    // Velocity converted into wheel-local coordinates
    private Vector3 wheelLocalVelocity;

    // Forward velocity component of the wheel
    private float forwardVelocity;

    // Sideways velocity component of the wheel
    // (important for future lateral tire physics)
    private float sidewaysVelocity;

    // Throttle value sent from CarController
    private float throttleInput;

    // Maximum engine force sent from CarController
    private float motorForce;

    // Called by CarController during initialization.
    // Gives this wheel access to the car's Rigidbody.
    public void Initialize(Rigidbody carRb)
    {
        rb = carRb;
    }

    // Called by CarController every physics frame
    // to update throttle and engine power.
    public void SetThrottle(float throttle, float force)
    {
        throttleInput = throttle;
        motorForce = force;
    }

    void Start()
    {
        // Calculate the limits of the suspension travel
        minLength = restLength - suspensionTravel;
        maxLength = restLength + suspensionTravel;

        // Initialize previous length so the first velocity calculation is stable
        previousSpringLength = restLength;
    }

    void FixedUpdate()
    {
        // Maximum distance the suspension ray must travel
        float rayLength = maxLength + wheelRadius;

        float compression;
        float springForce;
        float springVelocity;
        float damperForce;

        // Draw the suspension ray for debugging
        Debug.DrawRay(transform.position, -transform.up * rayLength, Color.red);

        // Raycast downward to detect ground contact
        if (Physics.Raycast(transform.position, -transform.up, out RaycastHit hit, rayLength))
        {
            // Draw ground normal at contact point
            Debug.DrawRay(hit.point, hit.normal, Color.green);

            // Convert raycast distance into actual suspension length
            currentSpringLength = hit.distance - wheelRadius;

            // Clamp suspension length within limits
            currentSpringLength = Mathf.Clamp(currentSpringLength, minLength, maxLength);

            // Calculate spring compression
            compression = restLength - currentSpringLength;

            // Hooke's law: spring force = compression * stiffness
            springForce = compression * springStrength;

            // Calculate suspension velocity
            springVelocity = (currentSpringLength - previousSpringLength) / Time.fixedDeltaTime;

            // Damper force resists suspension velocity
            damperForce = damperStrength * springVelocity;

            // Combine spring and damper forces
            suspensionForce = Mathf.Max(0f, springForce - damperForce) * hit.normal;

            // Visualize suspension force
            Debug.DrawRay(transform.position, suspensionForce * 0.0005f, Color.blue);

            // Apply suspension force at the wheel contact point
            rb.AddForceAtPosition(suspensionForce, hit.point);

            // Store current spring length for next frame
            previousSpringLength = currentSpringLength;

            // Get velocity of the rigidbody at the wheel contact point
            wheelWorldVelocity = rb.GetPointVelocity(hit.point);

            // Convert world velocity into wheel local space
            wheelLocalVelocity = transform.InverseTransformDirection(wheelWorldVelocity);

            // Extract forward and sideways velocity components
            forwardVelocity = wheelLocalVelocity.z;
            sidewaysVelocity = wheelLocalVelocity.x;

            // Debug visualization of velocity vectors
            Debug.DrawRay(hit.point, wheelWorldVelocity * 5f, Color.yellow);                 // world velocity
            Debug.DrawRay(hit.point, transform.forward * forwardVelocity * 5f, Color.blue); // forward velocity
            Debug.DrawRay(hit.point, transform.right * sidewaysVelocity * 5f, Color.cyan);  // sideways velocity

            // Apply engine force if this wheel is driven
            if (isDrivenWheel)
            {
                // Project forward direction onto the road surface
                // so the force follows the slope of the terrain
                Vector3 forwardDirection =
                    Vector3.ProjectOnPlane(transform.forward, hit.normal).normalized;

                // Calculate engine drive force
                Vector3 driveForce = forwardDirection * throttleInput * motorForce;

                // Apply drive force at the tire contact patch
                rb.AddForceAtPosition(driveForce, hit.point);
            }
        }
        else
        {
            // If the wheel is airborne, treat suspension as fully extended
            currentSpringLength = maxLength;

            // Reset previous length to avoid large velocity spikes when ground contact returns
            previousSpringLength = currentSpringLength;
        }
    }

    void Update()
    {
        // Currently unused.
        // All physics logic is handled in FixedUpdate.
    }
}